apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod-storage-14-3   
  namespace: kuber-14-3
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.45
    path: /mnt/nfs_prod