kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storage-14-3
  namespace: kuber-14-3
spec:
  storageClassName: "nfs"
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi